# Generated by Django 5.0 on 2023-12-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='gender',
            field=models.CharField(default='Prefer not to say', max_length=30),
        ),
    ]
