# Generated by Django 5.0 on 2023-12-15 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customuser_delete_registeration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
